language: ruby
rvm:
- 2.3.3
addons:
  ssh_known_hosts: cloud.elfgzp.cn
before_install:
- openssl aes-256-cbc -K $encrypted_f91baf41390f_key -iv $encrypted_f91baf41390f_iv
  -in id_ras_deploy.enc -out ~/.ssh/id_ras_deploy -d
- chmod 600 ~/.ssh/id_ras_deploy
- cp ssh_config ~/.ssh/config
script:
- bundle install
- bundle exec jekyll build
after_success:
- "./push.sh"
- ssh gzp@cloud.elfgzp.cn "cd ~/workspace/elfgzp.cn && source ~/.zshrc  &&
  git pull origin master && docker-compose build && docker-compose down && docker-compose
  up -d"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: rvlct7/EheArxc/avt7w25ynFn7n9KBwupNPvBw/GnqRsf0Q1RP1b6V3lrA23TWneGBYFQs9EwHJ1r7PB1ZAaPejaB11ei/Y184i4/bhaPa6aVqHt1+h4yVlNu6+ObX5XgWNG++6hp2+o81HgZ8QFcc75mL0PRj6M2DCqWPav5aNqXjkwFQCal3+wEFLVeYIXNx1rg4FjVK1iOqXIB5yVqJjwyy8L/yMZJv7ikI985t03x0p5HYdldJKNjUtUPomt4uS8M1ZdVqR0QJBWFL7gd8sWuA7j7JCm1OLGL4Q8hK0omKjPw4EMXTc4A52qNpytujAwbQGPKcVhQ35nUwAEHnCf/9HcXRQoo17zyyDp4HpTDef3CmWOBSsozeDOa93f1v429Pj0oUYBiVnZ/gPC0j1pmFK8mIu3I3bVI7Bvwwba8TsH2XCKLEq/vkUaMZ+OscfwiFTzveF0ah8N5eEkukHSEcRSwza2ZyUDXus87/hJs6Og4t1mKs1jM9mGO+ARS0wzTruGlAH/DbqVO2gSc54+zVfqPJc9NYw5m3xTUijYDXitvjp0shW1ktX6LaMhLd65aA5/XoeTrxCBIpPR3D6VBaD68gYjACKrCclnJYZuVFL/X+fy4SuWBE1kHqarCriPJxpoplwFsIPtLW/m/8MZjuaZQNiHO7k0oO5UxI=
